Controllers/SitemapAdminController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using IDeliverable.Seo.Helpers;
using IDeliverable.Seo.Models;
using IDeliverable.Seo.Services;
using IDeliverable.Seo.ViewModels;
using Orchard;
using Orchard.ContentManagement;
using Orchard.Environment.Extensions;
using Orchard.Localization;
using Orchard.Mvc;
using Orchard.UI.Admin;
using Orchard.UI.Navigation;
using Orchard.UI.Notify;

namespace IDeliverable.Seo.Controllers
{
    [OrchardFeature("IDeliverable.Seo.Sitemap")]
    [Admin]
    public class SitemapAdminController : Controller
    {
        private readonly IOrchardServices _orchardServices;
        private readonly ISitemapService _sitemapService;
        private readonly ISitemapSubmitter _sitemapSubmitter;

        public SitemapAdminController(IOrchardServices orchardServices, ISitemapService sitemapService, ISitemapSubmitter sitemapSubmitter)
        {
            _orchardServices = orchardServices;
            _sitemapService = sitemapService;
            _sitemapSubmitter = sitemapSubmitter;
            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        public ActionResult Index(PagerParameters pagerParameters, string provider = null, SitemapEntryOrderBy orderBy = SitemapEntryOrderBy.Provider)
        {
            var pager = new Pager(_orchardServices.WorkContext.CurrentSite, pagerParameters);
            var query = _sitemapService.GetEntries();

            if (!String.IsNullOrWhiteSpace(provider))
            {
                query = query.Where(x => x.ProviderName == provider);
            }

            switch (orderBy)
            {
                case SitemapEntryOrderBy.Priority:
                    query = query.OrderByDescending(x => x.Priority);
                    break;
                case SitemapEntryOrderBy.ChangeFrequency:
                    query = query.OrderBy(x => x.ChangeFrequency);
                    break;
                case SitemapEntryOrderBy.LastModified:
                    query = query.OrderByDescending(x => x.LastModifiedUtc);
                    break;
                case SitemapEntryOrderBy.Url:
                    query = query.OrderBy(x => x.Url);
                    break;
                case SitemapEntryOrderBy.Provider:
                default:
                    query = query.OrderBy(x => x.ProviderDisplayName);
                    break;
            }

            var totalCount = query.Count();
            var pageOfEntries = query.Skip(pager.GetStartIndex()).Take(pager.Page * pager.PageSize);
            var viewModel = new SitemapIndexViewModel
            {
                Handlers = _sitemapService.GetHandlers().ToArray(),
                Entries = pageOfEntries,
                SelectedProvider = provider,
                OrderBy = orderBy,
                Pager = _orchardServices.New.Pager(pager).TotalItemCount(totalCount)
            };
            return View(viewModel);
        }

        [FormValueRequired("submit.BulkEdit")]
        [ActionName("Index")]
        public ActionResult BulkEdit(SitemapIndexViewModel viewModel)
        {
            return RedirectToAction("Index");
        }

        [FormValueRequired("submit.Filter")]
        [ActionName("Index")]
        public ActionResult Filter(PagerParameters pagerParameters, SitemapIndexViewModel viewModel)
        {
            return RedirectToAction("Index", new
            {
                page = pagerParameters.Page,
                pageSize = pagerParameters.PageSize,
                provider = viewModel.SelectedProvider,
                orderBy = viewModel.OrderBy
            });
        }

        public ActionResult EditEntry(string url, string provider)
        {
            var entry = _sitemapService.GetEntry(url, provider);
            var editRouteValues = _sitemapService.GetEntryMetadata(entry).EditRouteValues;
            var editUrl = Url.RouteUrl(editRouteValues) + "?returnUrl=" + Url.Action("Index");
            return Redirect(editUrl);
        }

        public ActionResult Settings()
        {
            var settingsPart = _orchardServices.WorkContext.CurrentSite.As<SeoSitemapSettingsPart>();
            var viewModel = new SeoSitemapSettingsViewModel
            {
                MaxEntriesPerSitemap = settingsPart.MaxEntriesPerSitemap
            };
            return View(viewModel);
        }

        [HttpPost]
        [ActionName("Settings")]
        public ActionResult SaveSettings(SeoSitemapSettingsViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            var settingsPart = _orchardServices.WorkContext.CurrentSite.As<SeoSitemapSettingsPart>();
            settingsPart.MaxEntriesPerSitemap = viewModel.MaxEntriesPerSitemap;
            _orchardServices.Notifier.Information(T("Sitemap Settings have been saved."));
            return Redirect("Settings");
        }

        public ActionResult SearchEngines()
        {
            var settingsPart = _orchardServices.WorkContext.CurrentSite.As<SeoSitemapSettingsPart>();
            var viewModel = new SeoSitemapSearchEnginesViewModel
            {
                SearchEngines = settingsPart.SearchEngines.JoinLines(),
            };
            return View(viewModel);
        }

        [HttpPost]
        [FormValueRequired("submit.Save")]
        [ActionName("SearchEngines")]
        public ActionResult SaveSearchEngines(SeoSitemapSearchEnginesViewModel viewModel)
        {
            if(!ModelState.IsValid)
                return View(viewModel);

            var settingsPart = _orchardServices.WorkContext.CurrentSite.As<SeoSitemapSettingsPart>();
            settingsPart.SearchEngines = viewModel.SearchEngines.SplitLines();
            _orchardServices.Notifier.Information(T("Sitemap Search Engine Settings have been saved."));
            return Redirect("SearchEngines");
        }

        [HttpPost]
        [FormValueRequired("submit.SaveAndSubmit")]
        [ActionName("SearchEngines")]
        public ActionResult SaveSearchEnginesAndSubmit(SeoSitemapSearchEnginesViewModel viewModel)
        {
            var actionResult = SaveSearchEngines(viewModel);

            if (ModelState.IsValid)
            {
                var settingsPart = _orchardServices.WorkContext.CurrentSite.As<SeoSitemapSettingsPart>();
                var searchEngines = settingsPart.SearchEngines;
                var submissionResults = _sitemapSubmitter.SubmitSitemap(searchEngines);

                foreach (var result in submissionResults.Results)
                {
                    if(result.IsSuccessStatusCode)
                        _orchardServices.Notifier.Information(T("Successfully pinged {0}.", result.SearchEngineUrl));
                    else if(result.Exception == null)
                        _orchardServices.Notifier.Warning(T("Failed to ping {0}. Response status code: {1}", result.SearchEngineUrl, result.StatusCode));
                    else
                        _orchardServices.Notifier.Error(T("Failed to ping {0}. Exception: {1}", result.SearchEngineUrl, result.Exception.Message));
                }
            }

            return actionResult;
        }
    }
}

Views/SitemapAdmin/Index.cshtml
@using IDeliverable.Seo.Models;
@model IDeliverable.Seo.ViewModels.SitemapIndexViewModel
@{
    Layout.Title = T("Sitemap Entries");
}
@{
    Style.Include("admin-sitemap.css");
    Script.Require("ShapesBase");
}
@{
    var handlerOptions = Model.Handlers.Select(x => new SelectListItem {Text = x.DisplayName.ToString(), Value = x.Name, Selected = Model.SelectedProvider == x.Name});
}
<div class="manage">
    @Html.ActionLink(T("Add Custom Url").ToString(), "Create", "CustomSitemapEntry", new { Area = "IDeliverable.Seo" }, new { @class = "button primaryAction" })
</div>
@using (Html.BeginFormAntiForgeryPost()) {
    <fieldset class="bulk-actions">
        @Html.LabelFor(m => m.SelectedProvider, T("Filter by:"))
        @Html.DropDownListFor(m => m.SelectedProvider, handlerOptions, T("Any (show all)").ToString())
        <label for="orderResults" class="bulk-order">@T("Order by:")</label>
        <select id="orderResults" name="@Html.FieldNameFor(m => m.OrderBy)">
            @Html.SelectOption(Model.OrderBy, SitemapEntryOrderBy.Provider, T("Provider").ToString())
            @Html.SelectOption(Model.OrderBy, SitemapEntryOrderBy.Priority, T("Priority").ToString())
            @Html.SelectOption(Model.OrderBy, SitemapEntryOrderBy.ChangeFrequency, T("Change Frequency").ToString())
            @Html.SelectOption(Model.OrderBy, SitemapEntryOrderBy.LastModified, T("Last Modified").ToString())
            @Html.SelectOption(Model.OrderBy, SitemapEntryOrderBy.Url, T("Url").ToString())
        </select>
        <button type="submit" name="submit.Filter" value="yes">@T("Apply")</button>
    </fieldset>
    <table class="items">
        <thead>
            <tr>
                <th>@T("Url")</th>
                <th>@T("Change Frequency")</th>
                <th>@T("Priority")</th>
                <th>@T("Last Modified")</th>
                <th>@T("Provider")</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var entry in Model.Entries)
            {
                <tr>
                    <td>@entry.Url</td>
                    <td>@entry.ChangeFrequency</td>
                    <td>@(entry.Priority != null ? entry.Priority.Value.ToString("f1") : "")</td>
                    <td>@entry.LastModifiedUtc</td>
                    <td>@entry.ProviderName</td>
                    <td>
                        <a href="@Url.Action("EditEntry", "SitemapAdmin", new { Area = "IDeliverable.Seo", url = entry.Url, provider = entry.ProviderName })">@T("Edit")</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@Display(Model.Pager)

Views/SitemapAdmin/SearchEngines.cshtml
@model IDeliverable.Seo.ViewModels.SeoSitemapSearchEnginesViewModel
@{
    Layout.Title = T("Sitemap Settings");
}
@using (Html.BeginFormAntiForgeryPost())
{
    <fieldset>
        <legend>@T("Search Engines")</legend>
        <div class="form-group">
            @Html.TextAreaFor(m => m.SearchEngines, new { @class = "text large" })
            @Html.Hint(T("The search engine URLs to submit the sitemap to. Enter one search engine URL per line in the following format: http://searchengine.com/ping?sitemap={0}. The {0} placeholder will be automatically replaced with the actual URL to sitemap.xml.", "{0}"))
        </div>
    </fieldset>
    <fieldset>
        <button type="submit" name="submit.Save" value="submit.Save">@T("Save")</button>
        <button type="submit" name="submit.SaveAndSubmit" value="submit.SaveAndSubmit">@T("Save and Ping")</button>
        @Html.Hint(T("The Save and Ping button will ping the listed search engines above to let them know your sitemap has been updated."))
        @Html.Hint(T("TIP: Create a Workflow to periodically ping the search engines."))
    </fieldset>
}

Views/SitemapAdmin/Settings.cshtml
@model IDeliverable.Seo.ViewModels.SeoSitemapSettingsViewModel
@{
    Layout.Title = T("Sitemap Settings");
}
@using (Html.BeginFormAntiForgeryPost())
{
    <fieldset>
        <legend>@T("Multiple Sitemaps")</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.MaxEntriesPerSitemap, T("Maximum URLs Per Sitemap"))
            @Html.TextBoxFor(m => m.MaxEntriesPerSitemap, new {@class = "text medium"})
            @Html.Hint(T("If the number of URLs exceed this number, a sitemap index will be generated automatically."))
        </div>
    </fieldset>
    <fieldset>
        <button type="submit">@T("Save")</button>
    </fieldset>
}